"""add hotel_id to utility_bills

Revision ID: efa65d940ec4
Revises: dec5ae65e6f6
Create Date: 2025-05-19 19:06:53.335613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa65d940ec4'
down_revision: Union[str, None] = 'dec5ae65e6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utility_bills', sa.Column('hotel_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_utility_bills_hotel_id'), 'utility_bills', ['hotel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utility_bills_hotel_id'), table_name='utility_bills')
    op.drop_column('utility_bills', 'hotel_id')
    # ### end Alembic commands ###
